### ISSUE TITLE
Create publisher related features.

### ISSUE THREAD

**Issue by nuriu** [nuriu/cemiyet-backend#22]
**Base features**
- [x] Publisher entity.
- [x] Example publisher data to seeding.
- [x] Implement related exceptions.
   - [x] PublisherNotFoundException

**Queries**
- [x] List
   - [x] ListQuery
   - [x] ListHandler
   - [x] ListQueryValidator
- [x] Details
   - [x] DetailsQuery
   - [x] DetailsHandler
   - [x] DetailsQueryValidator

**Commands**
- [x] Add
   - [x] AddCommand
   - [x] AddHandler
   - [x] AddCommandValidator
- [x] Update
   - [x] UpdateCommand
   - [x] UpdateHandler
   - [x] UpdateCommandValidator
- [x] UpdatePartially
   - [x] UpdatePartiallyCommand
   - [x] UpdatePartiallyHandler
   - [x] UpdatePartiallyCommandValidator
- [x] DeleteOne
   - [x] DeleteOneCommand
   - [x] DeleteOneHandler
   - [x] DeleteOneCommandValidator
- [x] DeleteMany
   - [x] DeleteManyCommand
   - [x] DeleteManyHandler
   - [x] DeleteManyCommandValidator

**Tests**
- [x] Integration tests for controller.
   - [x] Add
   - [x] List
   - [x] Details
   - [x] Update
   - [x] UpdatePartially
   - [x] DeleteOne
   - [x] DeleteMany
- [x] Validator tests.
   - [x] AddCommandValidator
   - [x] ListQueryValidator
   - [x] DetailsQueryValidator
   - [x] UpdateCommandValidator
   - [x] UpdatePartiallyCommandValidator
   - [x] DeleteOneCommandValidator
   - [x] DeleteManyCommandValidator
